# Generated by Django 5.2.16 on 2026-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
